/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhooksIndexRouteImport } from './routes/webhooks.index'
import { Route as VerificationsIndexRouteImport } from './routes/verifications.index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ApiKeysIndexRouteImport } from './routes/api-keys.index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as VerificationsIdRouteImport } from './routes/verifications.$id'
import { Route as TemplatesIdRouteImport } from './routes/templates.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksIndexRoute = WebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationsIndexRoute = VerificationsIndexRouteImport.update({
  id: '/verifications/',
  path: '/verifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysIndexRoute = ApiKeysIndexRouteImport.update({
  id: '/api-keys/',
  path: '/api-keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationsIdRoute = VerificationsIdRouteImport.update({
  id: '/verifications/$id',
  path: '/verifications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdRoute = TemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/verifications/$id': typeof VerificationsIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/api-keys/': typeof ApiKeysIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/verifications/': typeof VerificationsIndexRoute
  '/webhooks/': typeof WebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/verifications/$id': typeof VerificationsIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/api-keys': typeof ApiKeysIndexRoute
  '/review': typeof ReviewIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/verifications': typeof VerificationsIndexRoute
  '/webhooks': typeof WebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/templates/$id': typeof TemplatesIdRoute
  '/verifications/$id': typeof VerificationsIdRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/api-keys/': typeof ApiKeysIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/verifications/': typeof VerificationsIndexRoute
  '/webhooks/': typeof WebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/templates/$id'
    | '/verifications/$id'
    | '/verify/$token'
    | '/api-keys/'
    | '/review/'
    | '/templates/'
    | '/verifications/'
    | '/webhooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/templates/$id'
    | '/verifications/$id'
    | '/verify/$token'
    | '/api-keys'
    | '/review'
    | '/templates'
    | '/verifications'
    | '/webhooks'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/templates/$id'
    | '/verifications/$id'
    | '/verify/$token'
    | '/api-keys/'
    | '/review/'
    | '/templates/'
    | '/verifications/'
    | '/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TemplatesIdRoute: typeof TemplatesIdRoute
  VerificationsIdRoute: typeof VerificationsIdRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  ApiKeysIndexRoute: typeof ApiKeysIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  VerificationsIndexRoute: typeof VerificationsIndexRoute
  WebhooksIndexRoute: typeof WebhooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/': {
      id: '/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof WebhooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifications/': {
      id: '/verifications/'
      path: '/verifications'
      fullPath: '/verifications/'
      preLoaderRoute: typeof VerificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys/': {
      id: '/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof ApiKeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifications/$id': {
      id: '/verifications/$id'
      path: '/verifications/$id'
      fullPath: '/verifications/$id'
      preLoaderRoute: typeof VerificationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id': {
      id: '/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof TemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TemplatesIdRoute: TemplatesIdRoute,
  VerificationsIdRoute: VerificationsIdRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  ApiKeysIndexRoute: ApiKeysIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  VerificationsIndexRoute: VerificationsIndexRoute,
  WebhooksIndexRoute: WebhooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
